/**
 * AI60 referral engine: Google Apps Script backend.
 * GENERATED by tools/build-gas.js. Edit assets/engine.js or apps-script/gas-adapter.js, then rebuild.
 * Paste this whole file into Extensions > Apps Script (Code.gs) of your Google Sheet. See SETUP.md.
 */
/*
 * AI60 referral engine — core logic.
 *
 * One file, three runtimes: the browser (demo mode, dashboard, simulator), Node
 * (tests) and Google Apps Script (apps-script/Code.gs is built from this file by
 * tools/build-gas.js). So: plain ES2015, no modules, no optional chaining.
 *
 * Data model (same shape everywhere):
 *   regs     {createdAt, code, name, phone, email, college, branch, gradYear, project,
 *             referredBy, channel, source, medium, campaign, flags}
 *   visits   {ts, session, ref, channel, source, medium, campaign}
 *   partners {createdAt, code, name, org, type, cost}   type: champion | club | paid | owned
 */
var AI60 = (function () {
  'use strict';

  var GOAL = 500;
  var FINAL_YEAR = 2027;
  var IST_OFFSET_MIN = 330;
  var CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  var PARTNER_PREFIX = { champion: 'CH', club: 'CL', paid: 'PD', owned: 'OW' };
  var CHANNELS = ['champion', 'club', 'referral', 'paid', 'owned', 'direct'];
  var CHANNEL_LABELS = {
    champion: 'Student champions',
    club: 'Club co-hosts',
    referral: 'Referral loop',
    paid: 'Paid shout-outs',
    owned: 'Owned / organic',
    direct: 'Direct / unknown'
  };
  var BRANCHES = ['CSE', 'IT', 'AI & DS / AI & ML', 'ECE', 'EEE', 'Mechanical', 'Civil', 'Other'];
  var PROJECTS = {
    resume: 'AI Resume Analyzer',
    quiz: 'Placement Quiz Bot',
    buddy: 'Study Buddy Chatbot',
    unsure: 'Not sure yet'
  };
  var MILESTONES = [
    { n: 3, reward: 'AI Project Starter Kit: prompts, templates and 3 more project ideas' },
    { n: 5, reward: 'Priority Q&A slot + "Campus Builder" certificate' },
    { n: 10, reward: '1:1 project review with a mentor + LinkedIn shout-out' }
  ];
  var TOP_PRIZES = [500, 300, 200];
  var DISPOSABLE = ['mailinator.com', 'tempmail.com', 'temp-mail.org', '10minutemail.com', 'guerrillamail.com',
    'yopmail.com', 'trashmail.com', 'getnada.com', 'sharklasers.com', 'dispostable.com', 'fakeinbox.com'];
  var RULES = {
    cprKill: 25,          // ₹ per sign-up above which a paid channel is stopped
    cprScale: 12,         // ₹ per sign-up at or below which it gets the reserve
    minCvr: 0.2,          // landing conversion floor per channel
    minFinalYear: 0.7,    // share of sign-ups that must be final-year
    minK: 0.2,            // viral coefficient floor from day 3
    burstCount: 5,        // this many referrals ...
    burstMinutes: 15,     // ... inside this window = review before rewards
    concentration: 0.35,  // one college above this share = diversify
    wayBehind: 0.75,
    behind: 0.9,
    ahead: 1.1
  };

  // ---------- small helpers ----------

  function clean(s, max) {
    s = String(s == null ? '' : s).replace(/[\u0000-\u001f\u007f]/g, '').trim();
    return s.slice(0, max || 80);
  }
  function normPhone(p) {
    var d = String(p == null ? '' : p).replace(/\D/g, '');
    return d.length > 10 ? d.slice(-10) : d;
  }
  function normEmail(e) { return String(e == null ? '' : e).trim().toLowerCase(); }
  function normCode(c) { return String(c == null ? '' : c).trim().toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 12); }
  function cap(w) { return w ? w.charAt(0).toUpperCase() + w.slice(1).toLowerCase() : ''; }
  function firstName(name) { return cap(String(name || '').trim().split(/\s+/)[0] || ''); }
  function publicName(name) {
    var parts = String(name || '').trim().split(/\s+/);
    var last = parts.length > 1 ? parts[parts.length - 1].charAt(0).toUpperCase() + '.' : '';
    return (cap(parts[0] || 'Someone') + ' ' + last).trim();
  }
  function collegeKey(c) { return String(c || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); }
  function randChars(n, rand) {
    var s = '';
    for (var i = 0; i < n; i++) s += CODE_ALPHABET.charAt(Math.floor(rand() * CODE_ALPHABET.length));
    return s;
  }
  // Stops a value from being read as a formula when written to a sheet or CSV.
  function safeCell(v) {
    if (typeof v === 'string' && /^[=+\-@\t\r]/.test(v)) return "'" + v;
    return v == null ? '' : v;
  }

  // ---------- dates (all campaign days are IST calendar days) ----------

  function dayKey(iso) {
    var t = typeof iso === 'number' ? iso : Date.parse(iso);
    return new Date(t + IST_OFFSET_MIN * 60000).toISOString().slice(0, 10);
  }
  function diffDays(a, b) { return Math.round((Date.parse(a + 'T00:00:00Z') - Date.parse(b + 'T00:00:00Z')) / 86400000); }
  function addDays(day, n) { return new Date(Date.parse(day + 'T00:00:00Z') + n * 86400000).toISOString().slice(0, 10); }
  // Epoch ms for an IST wall-clock time on a given day.
  function istTime(day, hour, minute) {
    return Date.parse(day + 'T00:00:00Z') + ((hour || 0) * 60 + (minute || 0) - IST_OFFSET_MIN) * 60000;
  }
  function clamp(x, lo, hi) { return Math.max(lo, Math.min(hi, x)); }

  // ---------- validation & registration ----------

  function validate(input) {
    input = input || {};
    var v = {
      name: clean(input.name, 60).replace(/\s+/g, ' '),
      phone: normPhone(input.phone),
      email: normEmail(input.email).slice(0, 100),
      college: clean(input.college, 80).replace(/\s+/g, ' '),
      branch: clean(input.branch, 40),
      gradYear: parseInt(input.gradYear, 10) || 0,
      project: PROJECTS[input.project] ? input.project : 'unsure'
    };
    var errors = {};
    if (v.name.length < 2 || !/[A-Za-zऀ-෿]/.test(v.name)) errors.name = 'Enter your full name';
    if (!/^[6-9]\d{9}$/.test(v.phone)) errors.phone = 'Enter a valid 10-digit WhatsApp number';
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v.email)) errors.email = 'Enter a valid email';
    if (v.college.length < 2) errors.college = 'Enter your college name';
    if (!v.branch) errors.branch = 'Pick your branch';
    if (v.gradYear < 2024 || v.gradYear > 2032) errors.gradYear = 'Pick your graduation year';
    return { ok: Object.keys(errors).length === 0, errors: errors, value: v };
  }

  function buildIndex(state) {
    var idx = { reg: {}, partner: {}, phone: {}, email: {} };
    (state.partners || []).forEach(function (p) { idx.partner[p.code] = p; });
    (state.regs || []).forEach(function (r) {
      idx.reg[r.code] = r;
      idx.phone[String(r.phone)] = r;
      idx.email[String(r.email).toLowerCase()] = r;
    });
    return idx;
  }

  function mediumToChannel(m) {
    if (/champion/.test(m)) return 'champion';
    if (/club/.test(m)) return 'club';
    if (/paid|cpc|sponsor|ads?$/.test(m)) return 'paid';
    if (/email|social|organic|owned|linkedin|newsletter/.test(m)) return 'owned';
    return 'direct';
  }

  // Who gets credit: a partner link beats a student link beats UTM tags.
  function attribute(ref, utm, idx) {
    utm = utm || {};
    var code = normCode(ref);
    var out = {
      referredBy: '',
      channel: 'direct',
      source: clean(utm.source, 40).toLowerCase(),
      medium: clean(utm.medium, 40).toLowerCase(),
      campaign: clean(utm.campaign, 40)
    };
    if (code && idx.partner[code]) { out.referredBy = code; out.channel = idx.partner[code].type; }
    else if (code && idx.reg[code]) { out.referredBy = code; out.channel = 'referral'; }
    else if (out.medium) out.channel = mediumToChannel(out.medium);
    return out;
  }

  function makeCode(name, taken, rand) {
    rand = rand || Math.random;
    var base = (firstName(name).toUpperCase().replace(/[^A-Z]/g, '') + 'XXXX').slice(0, 4);
    for (var i = 0; i < 50; i++) {
      var c = base + randChars(3, rand);
      if (!taken(c)) return c;
    }
    return base + randChars(6, rand);
  }

  function makePartnerCode(type, taken, rand) {
    rand = rand || Math.random;
    var prefix = PARTNER_PREFIX[type] || 'PT';
    for (var i = 0; i < 50; i++) {
      var c = prefix + '-' + randChars(4, rand);
      if (!taken(c)) return c;
    }
    return prefix + '-' + randChars(7, rand);
  }

  // Appends a registration to state.regs. Returns {ok, existing, row?, me} or {ok:false, errors}.
  function register(state, input, nowIso, rand) {
    input = input || {};
    if (clean(input.website)) return { ok: false, error: 'Could not register. Please try again.' }; // honeypot
    var check = validate(input);
    if (!check.ok) return { ok: false, errors: check.errors };
    var v = check.value;
    var idx = buildIndex(state);
    var existing = idx.phone[v.phone] || idx.email[v.email];
    if (existing) return { ok: true, existing: true, me: me(state, existing.code) };

    var a = attribute(input.ref, input.utm, idx);
    var flags = [];
    if (DISPOSABLE.indexOf(v.email.split('@')[1]) >= 0) flags.push('disposable-email');
    var row = {
      createdAt: nowIso || new Date().toISOString(),
      code: makeCode(v.name, function (c) { return !!(idx.reg[c] || idx.partner[c]); }, rand),
      name: v.name, phone: v.phone, email: v.email, college: v.college, branch: v.branch,
      gradYear: v.gradYear, project: v.project,
      referredBy: a.referredBy, channel: a.channel, source: a.source, medium: a.medium, campaign: a.campaign,
      flags: flags.join(' ')
    };
    state.regs = state.regs || [];
    state.regs.push(row);
    return { ok: true, existing: false, row: row, me: me(state, row.code) };
  }

  function createPartner(state, input, nowIso, rand) {
    input = input || {};
    var type = PARTNER_PREFIX[input.type] ? input.type : 'champion';
    var name = clean(input.name, 60);
    if (name.length < 2) return { ok: false, error: 'Partner name is required' };
    var idx = buildIndex(state);
    var row = {
      createdAt: nowIso || new Date().toISOString(),
      code: makePartnerCode(type, function (c) { return !!(idx.reg[c] || idx.partner[c]); }, rand),
      name: name,
      org: clean(input.org, 80),
      type: type,
      cost: Math.max(0, Math.round(Number(input.cost) || 0))
    };
    state.partners = state.partners || [];
    state.partners.push(row);
    return { ok: true, partner: row };
  }

  function visit(state, input, nowIso) {
    input = input || {};
    var a = attribute(input.ref, input.utm, buildIndex(state));
    var row = {
      ts: nowIso || new Date().toISOString(),
      session: clean(input.session, 24),
      ref: a.referredBy, channel: a.channel, source: a.source, medium: a.medium, campaign: a.campaign
    };
    state.visits = state.visits || [];
    state.visits.push(row);
    return { ok: true };
  }

  // ---------- public read models ----------

  // Verified referral credit per code: student links only, flagged sign-ups don't count.
  function referralCounts(regs) {
    var counts = {};
    (regs || []).forEach(function (r) {
      if (r.channel === 'referral' && r.referredBy && !r.flags) counts[r.referredBy] = (counts[r.referredBy] || 0) + 1;
    });
    return counts;
  }

  function nextMilestone(n) {
    for (var i = 0; i < MILESTONES.length; i++) if (n < MILESTONES[i].n) return MILESTONES[i];
    return null;
  }

  function me(state, code) {
    code = normCode(code);
    var idx = buildIndex(state);
    var r = idx.reg[code];
    if (!r) return { ok: false, error: 'Referral code not found' };
    var counts = referralCounts(state.regs);
    var n = counts[code] || 0;
    var rank = null;
    if (n > 0) rank = 1 + Object.keys(counts).filter(function (k) { return counts[k] > n && idx.reg[k]; }).length;
    return {
      ok: true, code: code, firstName: firstName(r.name), college: r.college,
      referrals: n, rank: rank, next: nextMilestone(n), total: (state.regs || []).length
    };
  }

  function refInfo(state, code) {
    code = normCode(code);
    if (!code) return { ok: false };
    var idx = buildIndex(state);
    var p = idx.partner[code];
    if (p) {
      if (p.type === 'club') return { ok: true, kind: 'club', label: p.org || p.name };
      if (p.type === 'champion') return { ok: true, kind: 'champion', label: firstName(p.name), org: p.org };
      return { ok: true, kind: p.type, label: '' };
    }
    var r = idx.reg[code];
    if (r) return { ok: true, kind: 'student', label: firstName(r.name), org: r.college };
    return { ok: false };
  }

  function groupColleges(regs) {
    var map = {};
    (regs || []).forEach(function (r) {
      var k = collegeKey(r.college);
      if (!k) return;
      var g = map[k] || (map[k] = { key: k, name: r.college, names: {}, count: 0, finalYear: 0 });
      g.count++;
      if (Number(r.gradYear) === FINAL_YEAR) g.finalYear++;
      g.names[r.college] = (g.names[r.college] || 0) + 1;
    });
    return Object.keys(map).map(function (k) {
      var g = map[k];
      g.name = Object.keys(g.names).sort(function (a, b) { return g.names[b] - g.names[a]; })[0];
      delete g.names;
      return g;
    }).sort(function (a, b) { return b.count - a.count || (a.name < b.name ? -1 : 1); });
  }

  function stats(state) {
    var regs = state.regs || [];
    var idx = buildIndex(state);
    var counts = referralCounts(regs);
    var colleges = groupColleges(regs);
    var top = Object.keys(counts).filter(function (c) { return idx.reg[c]; }).map(function (c) {
      return { name: publicName(idx.reg[c].name), college: idx.reg[c].college, count: counts[c] };
    }).sort(function (a, b) { return b.count - a.count || (a.name < b.name ? -1 : 1); }).slice(0, 10);
    return {
      ok: true, total: regs.length, goal: GOAL, colleges: colleges.length, topReferrers: top,
      topColleges: colleges.slice(0, 8).map(function (g) { return { college: g.name, count: g.count }; })
    };
  }

  // ---------- growth analytics (dashboard) ----------

  // Follows referral chains back to the partner (or channel) that started them.
  function rootResolver(regs, partnerByCode) {
    var byCode = {}, memo = {};
    regs.forEach(function (r) { byCode[r.code] = r; });
    return function root(r) {
      if (memo[r.code]) return memo[r.code];
      var cur = r, depth = 0, out = { channel: r.channel, partner: '' };
      while (cur && depth < 25) {
        if (cur.referredBy && partnerByCode[cur.referredBy]) {
          out = { channel: partnerByCode[cur.referredBy].type, partner: cur.referredBy };
          break;
        }
        if (cur.channel !== 'referral' || !byCode[cur.referredBy]) { out = { channel: cur.channel, partner: '' }; break; }
        cur = byCode[cur.referredBy];
        depth++;
      }
      memo[r.code] = out;
      return out;
    };
  }

  function burstOf(times, count, minutes) {
    times = times.slice().sort(function (a, b) { return a - b; });
    var best = 0, bestSpan = 0;
    for (var i = 0, j = 0; j < times.length; j++) {
      while (times[j] - times[i] > minutes * 60000) i++;
      if (j - i + 1 > best) { best = j - i + 1; bestSpan = Math.round((times[j] - times[i]) / 60000); }
    }
    return best >= count ? { n: best, minutes: Math.max(1, bestSpan) } : null;
  }

  function pct(x) { return Math.round(x * 100) + '%'; }
  function rupees(x) { return '₹' + Math.round(x).toLocaleString('en-IN'); }

  function analyze(data, opts) {
    opts = opts || {};
    var R = {};
    Object.keys(RULES).forEach(function (k) { R[k] = (opts.rules && opts.rules[k] != null) ? opts.rules[k] : RULES[k]; });
    var goal = opts.goal || GOAL;
    var finalYear = opts.finalYear || FINAL_YEAR;
    var days = opts.days || 7;
    var plan = opts.planTargets || [];
    var reserve = opts.reserve == null ? 200 : opts.reserve;
    var allRegs = (data.regs || []).slice().sort(function (a, b) { return Date.parse(a.createdAt) - Date.parse(b.createdAt); });
    var allVisits = data.visits || [];
    var partners = data.partners || [];

    var start = opts.campaignStart || (allRegs.length ? dayKey(allRegs[0].createdAt) : dayKey(Date.now()));
    var dayOf = function (iso) { return clamp(1 + diffDays(dayKey(iso), start), 1, days); };
    var asOf = opts.asOfDay || null;
    var nowMs = opts.now ? Date.parse(opts.now) : (asOf ? istTime(addDays(start, asOf - 1), 23, 59) : Date.now());
    var regs = allRegs.filter(function (r) { return Date.parse(r.createdAt) <= nowMs; });
    var visits = allVisits.filter(function (v) { return Date.parse(v.ts) <= nowMs; });
    var currentDay = asOf || clamp(1 + diffDays(dayKey(nowMs), start), 1, days);
    var total = regs.length;

    var partnerByCode = {};
    partners.forEach(function (p) { partnerByCode[p.code] = p; });
    var root = rootResolver(regs, partnerByCode);

    // Day series
    var series = [];
    for (var d = 1; d <= days; d++) {
      var by = {};
      CHANNELS.forEach(function (c) { by[c] = 0; });
      series.push({ day: d, date: addDays(start, d - 1), regs: 0, visits: 0, by: by, cum: null, plan: plan[d - 1] == null ? null : plan[d - 1] });
    }
    regs.forEach(function (r) {
      var s = series[dayOf(r.createdAt) - 1];
      s.regs++;
      s.by[CHANNELS.indexOf(r.channel) >= 0 ? r.channel : 'direct']++;
    });
    visits.forEach(function (v) { series[dayOf(v.ts) - 1].visits++; });
    var running = 0;
    series.forEach(function (s) { running += s.regs; if (s.day <= currentDay) s.cum = running; });

    // Channels
    var spendByChannel = {};
    partners.forEach(function (p) {
      if (Date.parse(p.createdAt) <= nowMs) spendByChannel[p.type] = (spendByChannel[p.type] || 0) + (Number(p.cost) || 0);
    });
    var channels = CHANNELS.map(function (c) {
      var cr = regs.filter(function (r) { return (r.channel || 'direct') === c; });
      var cv = visits.filter(function (v) { return (v.channel || 'direct') === c; }).length;
      var fy = cr.filter(function (r) { return Number(r.gradYear) === finalYear; }).length;
      var loop = regs.filter(function (r) { return r.channel === 'referral' && root(r).channel === c; }).length;
      var cost = spendByChannel[c] || 0;
      return {
        channel: c, label: CHANNEL_LABELS[c], visits: cv, regs: cr.length, loopRegs: loop,
        cvr: cv ? cr.length / cv : null, cost: cost, cpr: cost && cr.length ? cost / cr.length : (cost ? Infinity : null),
        finalYearPct: cr.length ? fy / cr.length : null, share: total ? cr.length / total : 0
      };
    }).filter(function (c) { return c.regs || c.visits || c.cost; });

    // Partners
    var partnerRows = partners.filter(function (p) { return Date.parse(p.createdAt) <= nowMs; }).map(function (p) {
      var direct = regs.filter(function (r) { return r.referredBy === p.code; }).length;
      var downstream = regs.filter(function (r) { return r.channel === 'referral' && root(r).partner === p.code; }).length;
      var pv = visits.filter(function (v) { return v.ref === p.code; }).length;
      var cost = Number(p.cost) || 0;
      var ageHours = (nowMs - Date.parse(p.createdAt)) / 3600000;
      var all = direct + downstream;
      return {
        code: p.code, name: p.name, org: p.org, type: p.type, cost: cost, visits: pv,
        direct: direct, downstream: downstream, total: all, cvr: pv ? direct / pv : null,
        cpr: cost ? (all ? cost / all : Infinity) : null, ageHours: ageHours, status: 'active'
      };
    });
    var fieldRows = partnerRows.filter(function (p) { return p.type === 'champion' || p.type === 'club'; })
      .sort(function (a, b) { return b.total - a.total; });
    var topCut = Math.max(1, Math.ceil(fieldRows.filter(function (p) { return p.total > 0; }).length * 0.2));
    fieldRows.forEach(function (p, i) {
      if (p.ageHours >= 24 && p.direct === 0) p.status = 'inactive';
      else if (i < topCut && p.total > 0) p.status = 'top';
    });
    partnerRows.forEach(function (p) {
      if (p.type !== 'paid') return;
      if (p.ageHours < 24) p.status = 'learning';
      else if (p.cpr > R.cprKill) p.status = 'kill';
      else if (p.cpr <= R.cprScale) p.status = 'scale';
      else p.status = 'watch';
    });
    partnerRows.sort(function (a, b) { return b.total - a.total || (a.code < b.code ? -1 : 1); });

    // Student referrers
    var counts = referralCounts(regs);
    var regByCode = {};
    regs.forEach(function (r) { regByCode[r.code] = r; });
    var refTimes = {};
    regs.forEach(function (r) {
      if (r.channel === 'referral' && r.referredBy) (refTimes[r.referredBy] = refTimes[r.referredBy] || []).push(Date.parse(r.createdAt));
    });
    var referrers = Object.keys(refTimes).filter(function (c) { return regByCode[c]; }).map(function (c) {
      var r = regByCode[c];
      var burst = burstOf(refTimes[c], R.burstCount, R.burstMinutes);
      var flagged = refTimes[c].length - (counts[c] || 0);
      return {
        code: c, name: r.name, college: r.college, count: counts[c] || 0, attempts: refTimes[c].length,
        burst: burst, flaggedReferrals: flagged, next: nextMilestone(counts[c] || 0)
      };
    }).sort(function (a, b) { return b.count - a.count || (a.name < b.name ? -1 : 1); });
    var near = 0;
    regs.forEach(function (r) {
      var n = counts[r.code] || 0;
      MILESTONES.forEach(function (m) { if (n === m.n - 1) near++; });
    });
    var referralRegs = regs.filter(function (r) { return r.channel === 'referral'; }).length;
    var sharers = Object.keys(refTimes).length;

    // Mix
    var colleges = groupColleges(regs);
    var projects = {};
    Object.keys(PROJECTS).forEach(function (k) { projects[k] = 0; });
    var gradYears = {};
    regs.forEach(function (r) {
      projects[PROJECTS[r.project] ? r.project : 'unsure']++;
      var y = Number(r.gradYear) || 'Unknown';
      gradYears[y] = (gradYears[y] || 0) + 1;
    });
    var finalYearCount = gradYears[finalYear] || 0;
    var spend = Object.keys(spendByChannel).reduce(function (s, k) { return s + spendByChannel[k]; }, 0);
    var k = total ? referralRegs / total : 0;

    var today = series[currentDay - 1];
    var cum = today ? (today.cum || 0) : total;
    // Plan line pro-rated to the hour, so a live check at 2 PM isn't judged against the 11:59 PM target.
    var target = null;
    if (plan[currentDay - 1] != null) {
      var prevTarget = currentDay > 1 ? (plan[currentDay - 2] || 0) : 0;
      var frac = asOf ? 1 : clamp((nowMs - istTime(addDays(start, currentDay - 1), 0, 0)) / 86400000, 0, 1);
      target = Math.round(prevTarget + (plan[currentDay - 1] - prevTarget) * frac);
    }
    var kpis = {
      total: total, goal: goal, progress: goal ? total / goal : 0,
      day: currentDay, days: days, target: target, vsPlan: target ? cum / target - 1 : null,
      today: today ? today.regs : 0, yesterday: currentDay > 1 ? series[currentDay - 2].regs : null,
      visits: visits.length, cvr: visits.length ? total / visits.length : null,
      k: k, referralRegs: referralRegs, sharers: sharers,
      shareRate: total ? sharers / total : 0,
      spend: spend, costPerSignup: total ? spend / total : null,
      finalYearPct: total ? finalYearCount / total : null,
      colleges: colleges.length
    };

    // ---------- today's decisions: deterministic rules, no model in the loop ----------
    var recs = [];
    if (target) {
      var ratio = cum / target;
      var gap = cum + ' vs ' + target + ' planned by ' + (asOf ? 'end of day ' + currentDay : 'now (day ' + currentDay + ')');
      if (ratio < R.wayBehind) recs.push({ level: 'critical', title: 'Well behind plan: ' + gap,
        action: 'Pull both backup levers today: recruit 5 backup champions in the top 3 colleges and run a second WhatsApp wave through the top 5 champions.' });
      else if (ratio < R.behind) recs.push({ level: 'warning', title: 'Behind plan: ' + gap,
        action: 'Ask the top 5 champions for a second forward today and nudge everyone who is one referral from a reward.' });
      else if (ratio >= R.ahead) recs.push({ level: 'good', title: 'Ahead of plan: ' + gap,
        action: 'Shift effort to show-up: calendar invites plus D-1, 2-hour and 15-minute WhatsApp reminders.' });
      else recs.push({ level: 'good', title: 'On plan: ' + gap, action: 'Keep the cadence. Re-check at 9 PM.' });
    }
    partnerRows.filter(function (p) { return p.type === 'paid'; }).forEach(function (p) {
      var label = p.name + (p.org ? ' (' + p.org + ')' : '');
      var cprText = isFinite(p.cpr) ? rupees(p.cpr) : 'no sign-ups';
      if (p.status === 'kill') recs.push({ level: 'critical', title: 'Kill ' + label + ': ' + rupees(p.cost) + ' bought ' + p.total + ' sign-ups (' + cprText + ' each)',
        action: 'Stop spend here. Move what is left of the budget to referral rewards.' });
      else if (p.status === 'scale' && currentDay < days) recs.push({ level: 'good', title: 'Scale ' + label + ': ' + cprText + ' per sign-up',
        action: 'Put the ' + rupees(reserve) + ' reserve here for the last-call push.' });
    });
    var inactive = fieldRows.filter(function (p) { return p.status === 'inactive'; });
    if (inactive.length) recs.push({ level: 'warning',
      title: inactive.length + (inactive.length === 1 ? ' partner has' : ' partners have') + ' 0 sign-ups after 24 hours',
      detail: inactive.slice(0, 6).map(function (p) { return p.name + ' (' + p.code + ')'; }).join(', '),
      action: 'Send them today\'s ready-made forward. Replace with a backup champion if still at 0 tomorrow.' });
    if (currentDay >= 3 && total >= 30 && k < R.minK) recs.push({ level: 'warning',
      title: 'Referral loop is weak: k = ' + k.toFixed(2) + ' (plan assumes 0.30)',
      action: 'Send a "you are one referral away" nudge to ' + near + ' students and pin the college leaderboard in champion groups.' });
    else if (near > 0) recs.push({ level: 'info', title: near + (near === 1 ? ' student is' : ' students are') + ' one referral away from a reward',
      action: 'Nudge them on WhatsApp with their personal link. These are the cheapest sign-ups available.' });
    if (total >= 30 && kpis.finalYearPct < R.minFinalYear) {
      var leak = channels.filter(function (c) { return c.regs >= 10; })
        .sort(function (a, b) { return a.finalYearPct - b.finalYearPct; })[0];
      recs.push({ level: 'warning', title: 'Only ' + pct(kpis.finalYearPct) + ' of sign-ups are final-year',
        action: 'Juniors are leaking in' + (leak ? ' through ' + leak.label.toLowerCase() : '') + '. Lead the copy with "for the 2027 batch".' });
    }
    // Paid traffic is cold and judged on ₹ per sign-up instead.
    channels.forEach(function (c) {
      if (c.channel !== 'paid' && c.visits >= 50 && c.cvr < R.minCvr) recs.push({ level: 'warning',
        title: c.label + ': only ' + pct(c.cvr) + ' of visitors sign up',
        action: 'Message mismatch. Make the forward promise exactly what the page headline says.' });
    });
    referrers.filter(function (r) { return r.burst; }).forEach(function (r) {
      recs.push({ level: 'critical', title: 'Review ' + publicName(r.name) + ' before rewards: ' + r.burst.n + ' referrals in ' + r.burst.minutes + ' min',
        action: 'Hold their milestone and prize until the referred students show up to the workshop.' });
    });
    if (total >= 50 && colleges.length && colleges[0].count / total > R.concentration) recs.push({ level: 'info',
      title: pct(colleges[0].count / total) + ' of sign-ups come from ' + colleges[0].name,
      action: 'Ask its champions to introduce one peer each at another college.' });
    var order = { critical: 0, warning: 1, good: 2, info: 3 };
    recs.sort(function (a, b) { return order[a.level] - order[b.level]; });

    return {
      start: start, currentDay: currentDay, kpis: kpis, series: series, channels: channels,
      partners: partnerRows, referrers: referrers, colleges: colleges, projects: projects,
      gradYears: gradYears, recommendations: recs, near: near,
      regs: regs, visits: visits
    };
  }

  // ---------- CSV ----------

  function toCSV(rows, cols) {
    var esc = function (v) {
      v = safeCell(v);
      v = String(v);
      return /[",\n\r]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
    };
    return [cols.join(',')].concat(rows.map(function (r) {
      return cols.map(function (c) { return esc(r[c]); }).join(',');
    })).join('\r\n');
  }

  return {
    GOAL: GOAL, FINAL_YEAR: FINAL_YEAR, CHANNELS: CHANNELS, CHANNEL_LABELS: CHANNEL_LABELS,
    BRANCHES: BRANCHES, PROJECTS: PROJECTS, MILESTONES: MILESTONES, TOP_PRIZES: TOP_PRIZES, RULES: RULES,
    PARTNER_PREFIX: PARTNER_PREFIX,
    clean: clean, normPhone: normPhone, normEmail: normEmail, normCode: normCode,
    firstName: firstName, publicName: publicName, safeCell: safeCell,
    dayKey: dayKey, addDays: addDays, diffDays: diffDays, istTime: istTime,
    validate: validate, attribute: attribute, buildIndex: buildIndex,
    makeCode: makeCode, makePartnerCode: makePartnerCode,
    register: register, createPartner: createPartner, visit: visit,
    referralCounts: referralCounts, nextMilestone: nextMilestone,
    me: me, refInfo: refInfo, stats: stats, groupColleges: groupColleges,
    analyze: analyze, toCSV: toCSV
  };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = AI60;


/* ================================================================
 * Google Apps Script adapter: Google Sheets in, JSON out.
 * The engine above (AI60) does all the logic; this part only reads and
 * writes the three sheets and turns requests into engine calls.
 * ================================================================ */

var SHEETS = {
  regs: { name: 'Registrations', cols: ['createdAt', 'code', 'name', 'phone', 'email', 'college', 'branch', 'gradYear', 'project', 'referredBy', 'channel', 'source', 'medium', 'campaign', 'flags'] },
  visits: { name: 'Visits', cols: ['ts', 'session', 'ref', 'channel', 'source', 'medium', 'campaign'] },
  partners: { name: 'Partners', cols: ['createdAt', 'code', 'name', 'org', 'type', 'cost'] }
};

/** Run this once from the editor. It creates the sheets and prints the admin key. */
function setup() {
  Object.keys(SHEETS).forEach(function (k) { sheet_(SHEETS[k]); });
  var props = PropertiesService.getScriptProperties();
  var key = props.getProperty('ADMIN_KEY');
  if (!key) {
    key = Utilities.getUuid().replace(/-/g, '').slice(0, 16);
    props.setProperty('ADMIN_KEY', key);
  }
  Logger.log('Setup done. Admin key for the growth console: ' + key);
  return key;
}

function doGet(e) {
  var p = (e && e.parameter) || {};
  return respond_(function () {
    if (p.action === 'stats') return cached_('stats', 60, function () { return AI60.stats(load_(['regs', 'partners'])); });
    if (p.action === 'me') return AI60.me(load_(['regs', 'partners']), p.code);
    if (p.action === 'ref') return AI60.refInfo(load_(['regs', 'partners']), p.code);
    return { ok: true, service: 'ai60-referral-engine' };
  });
}

function doPost(e) {
  var body = {};
  try { body = JSON.parse((e && e.postData && e.postData.contents) || '{}'); } catch (err) { body = {}; }
  return respond_(function () {
    switch (body.action) {
      case 'register':
        return withLock_(function () {
          var state = load_(['regs', 'partners']);
          var res = AI60.register(state, body, new Date().toISOString());
          if (res.ok && res.row) {
            append_(SHEETS.regs, res.row);
            CacheService.getScriptCache().remove('stats');
          }
          delete res.row;
          return res;
        });
      case 'visit':
        // Raw and cheap: channel is resolved when the console reads visits.
        append_(SHEETS.visits, {
          ts: new Date().toISOString(),
          session: AI60.clean(body.session, 24),
          ref: AI60.normCode(body.ref),
          channel: '',
          source: AI60.clean(body.utm && body.utm.source, 40).toLowerCase(),
          medium: AI60.clean(body.utm && body.utm.medium, 40).toLowerCase(),
          campaign: AI60.clean(body.utm && body.utm.campaign, 40)
        });
        return { ok: true };
      case 'admin':
        checkKey_(body.key);
        var s = load_(['regs', 'visits', 'partners']);
        var idx = AI60.buildIndex(s);
        s.visits.forEach(function (v) {
          if (v.channel) return;
          var a = AI60.attribute(v.ref, { source: v.source, medium: v.medium, campaign: v.campaign }, idx);
          v.channel = a.channel;
          v.ref = a.referredBy;
        });
        return { ok: true, regs: s.regs, visits: s.visits, partners: s.partners };
      case 'partner':
        checkKey_(body.key);
        return withLock_(function () {
          var state = load_(['regs', 'partners']);
          var res = AI60.createPartner(state, body, new Date().toISOString());
          if (res.ok) append_(SHEETS.partners, res.partner);
          return res;
        });
      default:
        return { ok: false, error: 'Unknown action' };
    }
  });
}

// ---------- helpers ----------

function respond_(fn) {
  var out;
  try { out = fn(); } catch (err) { out = { ok: false, error: String((err && err.message) || err) }; }
  return ContentService.createTextOutput(JSON.stringify(out)).setMimeType(ContentService.MimeType.JSON);
}

function checkKey_(key) {
  var expected = PropertiesService.getScriptProperties().getProperty('ADMIN_KEY');
  if (!expected || String(key || '') !== expected) throw new Error('Wrong admin key');
}

function withLock_(fn) {
  var lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try { return fn(); } finally { lock.releaseLock(); }
}

function cached_(key, seconds, fn) {
  var cache = CacheService.getScriptCache();
  var hit = cache.get(key);
  if (hit) return JSON.parse(hit);
  var value = fn();
  try { cache.put(key, JSON.stringify(value), seconds); } catch (err) { /* over 100 KB: skip caching */ }
  return value;
}

function sheet_(def) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sh = ss.getSheetByName(def.name);
  if (!sh) {
    sh = ss.insertSheet(def.name);
    // Plain-text columns: phone numbers keep their digits, ISO dates stay strings.
    sh.getRange(1, 1, sh.getMaxRows(), def.cols.length).setNumberFormat('@');
    sh.getRange(1, 1, 1, def.cols.length).setValues([def.cols]).setFontWeight('bold');
    sh.setFrozenRows(1);
  }
  return sh;
}

function load_(names) {
  var out = { regs: [], visits: [], partners: [] };
  names.forEach(function (n) { out[n] = readAll_(SHEETS[n]); });
  return out;
}

function readAll_(def) {
  var sh = sheet_(def);
  var last = sh.getLastRow();
  if (last < 2) return [];
  return sh.getRange(2, 1, last - 1, def.cols.length).getValues().map(function (row) {
    var o = {};
    def.cols.forEach(function (c, i) {
      var v = row[i];
      if (v instanceof Date) v = v.toISOString();
      if (typeof v === 'string' && v.charAt(0) === "'") v = v.slice(1);
      o[c] = v === null || v === undefined ? '' : (typeof v === 'number' ? String(v) : v);
    });
    return o;
  });
}

function append_(def, obj) {
  sheet_(def).appendRow(def.cols.map(function (c) { return AI60.safeCell(obj[c] == null ? '' : String(obj[c])); }));
}
