// Builds apps-script/Code.gs = assets/engine.js + apps-script/gas-adapter.js
// Run: node tools/build-gas.js
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const engine = fs.readFileSync(path.join(root, 'assets', 'engine.js'), 'utf8');
const adapter = fs.readFileSync(path.join(root, 'apps-script', 'gas-adapter.js'), 'utf8');
const header = [
  '/**',
  ' * AI60 referral engine: Google Apps Script backend.',
  ' * GENERATED by tools/build-gas.js. Edit assets/engine.js or apps-script/gas-adapter.js, then rebuild.',
  ' * Paste this whole file into Extensions > Apps Script (Code.gs) of your Google Sheet. See SETUP.md.',
  ' */',
  ''
].join('\n');

fs.writeFileSync(path.join(root, 'apps-script', 'Code.gs'), header + engine + '\n\n' + adapter);
console.log('Wrote apps-script/Code.gs');
